# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factorial.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='factorial.proto',
  package='factorial_checker',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x61\x63torial.proto\x12\x11\x66\x61\x63torial_checker\"\x1e\n\rNumberRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\" \n\x0eNumberResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\"0\n\x0c\x43heckRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfactorial\x18\x02 \x01(\x03\"\x1f\n\rCheckResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xc7\x01\n\x10\x46\x61\x63torialChecker\x12\\\n\x13RequestRandomNumber\x12 .factorial_checker.NumberRequest\x1a!.factorial_checker.NumberResponse\"\x00\x12U\n\x0e\x43heckFactorial\x12\x1f.factorial_checker.CheckRequest\x1a .factorial_checker.CheckResponse\"\x00\x62\x06proto3'
)




_NUMBERREQUEST = _descriptor.Descriptor(
  name='NumberRequest',
  full_name='factorial_checker.NumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='factorial_checker.NumberRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=68,
)


_NUMBERRESPONSE = _descriptor.Descriptor(
  name='NumberResponse',
  full_name='factorial_checker.NumberResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='factorial_checker.NumberResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=102,
)


_CHECKREQUEST = _descriptor.Descriptor(
  name='CheckRequest',
  full_name='factorial_checker.CheckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='factorial_checker.CheckRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='factorial', full_name='factorial_checker.CheckRequest.factorial', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=152,
)


_CHECKRESPONSE = _descriptor.Descriptor(
  name='CheckResponse',
  full_name='factorial_checker.CheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='factorial_checker.CheckResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['NumberRequest'] = _NUMBERREQUEST
DESCRIPTOR.message_types_by_name['NumberResponse'] = _NUMBERRESPONSE
DESCRIPTOR.message_types_by_name['CheckRequest'] = _CHECKREQUEST
DESCRIPTOR.message_types_by_name['CheckResponse'] = _CHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumberRequest = _reflection.GeneratedProtocolMessageType('NumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERREQUEST,
  '__module__' : 'factorial_pb2'
  # @@protoc_insertion_point(class_scope:factorial_checker.NumberRequest)
  })
_sym_db.RegisterMessage(NumberRequest)

NumberResponse = _reflection.GeneratedProtocolMessageType('NumberResponse', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERRESPONSE,
  '__module__' : 'factorial_pb2'
  # @@protoc_insertion_point(class_scope:factorial_checker.NumberResponse)
  })
_sym_db.RegisterMessage(NumberResponse)

CheckRequest = _reflection.GeneratedProtocolMessageType('CheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKREQUEST,
  '__module__' : 'factorial_pb2'
  # @@protoc_insertion_point(class_scope:factorial_checker.CheckRequest)
  })
_sym_db.RegisterMessage(CheckRequest)

CheckResponse = _reflection.GeneratedProtocolMessageType('CheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRESPONSE,
  '__module__' : 'factorial_pb2'
  # @@protoc_insertion_point(class_scope:factorial_checker.CheckResponse)
  })
_sym_db.RegisterMessage(CheckResponse)



_FACTORIALCHECKER = _descriptor.ServiceDescriptor(
  name='FactorialChecker',
  full_name='factorial_checker.FactorialChecker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=188,
  serialized_end=387,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestRandomNumber',
    full_name='factorial_checker.FactorialChecker.RequestRandomNumber',
    index=0,
    containing_service=None,
    input_type=_NUMBERREQUEST,
    output_type=_NUMBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckFactorial',
    full_name='factorial_checker.FactorialChecker.CheckFactorial',
    index=1,
    containing_service=None,
    input_type=_CHECKREQUEST,
    output_type=_CHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACTORIALCHECKER)

DESCRIPTOR.services_by_name['FactorialChecker'] = _FACTORIALCHECKER

# @@protoc_insertion_point(module_scope)
