# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reservations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reservations.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12reservations.proto\"\x1d\n\rReservationId\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"o\n\x0bReservation\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x18\n\x10number_of_diners\x18\x03 \x01(\x05\x12\x13\n\x0b\x63lient_name\x18\x04 \x01(\t\x12\x15\n\rcontact_phone\x18\x05 \x01(\t\"b\n\x13ReservationResponse\x12\x17\n\x06result\x18\x01 \x01(\x0e\x32\x07.Result\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\x12!\n\x0breservation\x18\x03 \x01(\x0b\x32\x0c.Reservation\":\n\x0e\x43\x61ncelResponse\x12\x17\n\x06result\x18\x01 \x01(\x0e\x32\x07.Result\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\"\r\n\x0bListRequest\"6\n\x10ReservationsList\x12\"\n\x0creservations\x18\x01 \x03(\x0b\x32\x0c.Reservation*\x1b\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xea\x01\n\x0cReservations\x12\x35\n\x0fmakeReservation\x12\x0c.Reservation\x1a\x14.ReservationResponse\x12\x38\n\x10\x63heckReservation\x12\x0e.ReservationId\x1a\x14.ReservationResponse\x12\x34\n\x11\x63\x61ncelReservation\x12\x0e.ReservationId\x1a\x0f.CancelResponse\x12\x33\n\x10listReservations\x12\x0c.ListRequest\x1a\x11.ReservationsListb\x06proto3'
)

_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=397,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_RESULT)

Result = enum_type_wrapper.EnumTypeWrapper(_RESULT)
OK = 0
ERROR = 1



_RESERVATIONID = _descriptor.Descriptor(
  name='ReservationId',
  full_name='ReservationId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='ReservationId.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=51,
)


_RESERVATION = _descriptor.Descriptor(
  name='Reservation',
  full_name='Reservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='Reservation.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='Reservation.time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='number_of_diners', full_name='Reservation.number_of_diners', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_name', full_name='Reservation.client_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contact_phone', full_name='Reservation.contact_phone', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=164,
)


_RESERVATIONRESPONSE = _descriptor.Descriptor(
  name='ReservationResponse',
  full_name='ReservationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ReservationResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='ReservationResponse.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reservation', full_name='ReservationResponse.reservation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=264,
)


_CANCELRESPONSE = _descriptor.Descriptor(
  name='CancelResponse',
  full_name='CancelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='CancelResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='details', full_name='CancelResponse.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=324,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=339,
)


_RESERVATIONSLIST = _descriptor.Descriptor(
  name='ReservationsList',
  full_name='ReservationsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reservations', full_name='ReservationsList.reservations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=395,
)

_RESERVATIONRESPONSE.fields_by_name['result'].enum_type = _RESULT
_RESERVATIONRESPONSE.fields_by_name['reservation'].message_type = _RESERVATION
_CANCELRESPONSE.fields_by_name['result'].enum_type = _RESULT
_RESERVATIONSLIST.fields_by_name['reservations'].message_type = _RESERVATION
DESCRIPTOR.message_types_by_name['ReservationId'] = _RESERVATIONID
DESCRIPTOR.message_types_by_name['Reservation'] = _RESERVATION
DESCRIPTOR.message_types_by_name['ReservationResponse'] = _RESERVATIONRESPONSE
DESCRIPTOR.message_types_by_name['CancelResponse'] = _CANCELRESPONSE
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['ReservationsList'] = _RESERVATIONSLIST
DESCRIPTOR.enum_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReservationId = _reflection.GeneratedProtocolMessageType('ReservationId', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONID,
  '__module__' : 'reservations_pb2'
  # @@protoc_insertion_point(class_scope:ReservationId)
  })
_sym_db.RegisterMessage(ReservationId)

Reservation = _reflection.GeneratedProtocolMessageType('Reservation', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATION,
  '__module__' : 'reservations_pb2'
  # @@protoc_insertion_point(class_scope:Reservation)
  })
_sym_db.RegisterMessage(Reservation)

ReservationResponse = _reflection.GeneratedProtocolMessageType('ReservationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONRESPONSE,
  '__module__' : 'reservations_pb2'
  # @@protoc_insertion_point(class_scope:ReservationResponse)
  })
_sym_db.RegisterMessage(ReservationResponse)

CancelResponse = _reflection.GeneratedProtocolMessageType('CancelResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANCELRESPONSE,
  '__module__' : 'reservations_pb2'
  # @@protoc_insertion_point(class_scope:CancelResponse)
  })
_sym_db.RegisterMessage(CancelResponse)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'reservations_pb2'
  # @@protoc_insertion_point(class_scope:ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ReservationsList = _reflection.GeneratedProtocolMessageType('ReservationsList', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONSLIST,
  '__module__' : 'reservations_pb2'
  # @@protoc_insertion_point(class_scope:ReservationsList)
  })
_sym_db.RegisterMessage(ReservationsList)



_RESERVATIONS = _descriptor.ServiceDescriptor(
  name='Reservations',
  full_name='Reservations',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=427,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='makeReservation',
    full_name='Reservations.makeReservation',
    index=0,
    containing_service=None,
    input_type=_RESERVATION,
    output_type=_RESERVATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='checkReservation',
    full_name='Reservations.checkReservation',
    index=1,
    containing_service=None,
    input_type=_RESERVATIONID,
    output_type=_RESERVATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='cancelReservation',
    full_name='Reservations.cancelReservation',
    index=2,
    containing_service=None,
    input_type=_RESERVATIONID,
    output_type=_CANCELRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listReservations',
    full_name='Reservations.listReservations',
    index=3,
    containing_service=None,
    input_type=_LISTREQUEST,
    output_type=_RESERVATIONSLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESERVATIONS)

DESCRIPTOR.services_by_name['Reservations'] = _RESERVATIONS

# @@protoc_insertion_point(module_scope)
